In [1]:
pip install pandas sqlalchemy psycopg2-binary jupyter

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: sqlalchemy in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.0.44)
Requirement already satisfied: psycopg2-binary in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.9.11)
Requirement already satisfied: jupyter in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (1.1.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: notebook in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (7.5.5)
Requirement already satisfied: jupyter-console in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipykernel in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (6.30.1)
Requirement already satisfied: ipywidgets in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (8.1.8)
Requirement already satisfied: jupyterlab in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter) (4.5.7)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (1.8.16)
Requirement already satisfied: ipython>=7.23.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (9.4.0)
Requirement already satisfied: jupyter-client>=8.0.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (5.8.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (0.1.7)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (26.2)
Requirement already satisfied: psutil>=5.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (7.0.0)
Requirement already satisfied: pyzmq>=25 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (27.0.2)
Requirement already satisfied: tornado>=6.2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (6.5.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.19.2)
Requirement already satisfied: stack_data in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.5)
Requirement already satisfied: platformdirs>=2.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (311)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipywidgets->jupyter) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from ipywidgets->jupyter) (3.0.16)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (2.0.5)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab->jupyter) (82.0.1)
Requirement already satisfied: anyio in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.10.0)
Requirement already satisfied: certifi in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2.10)
Requirement already satisfied: h11>=0.16 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.3)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.22.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)
Requirement already satisfied: requests>=2.31 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.32.4)
Requirement already satisfied: sniffio>=1.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.36.2)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.27.1)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.2)
Requirement already satisfied: rfc3339-validator in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (24.11.1)
Requirement already satisfied: beautifulsoup4 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.2.0)
Requirement already satisfied: defusedxml in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.5.0)
Requirement already satisfied: lark>=1.2.2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.2.2)
Requirement already satisfied: cffi>=1.0.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.17.1)
Requirement already satisfied: pycparser in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.22)
Requirement already satisfied: soupsieve>1.2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.8)
Requirement already satisfied: arrow>=0.15.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.9.0.20250822)
Requirement already satisfied: executing>=1.2.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:postgres@localhost:5433/source_db"
)

df = pd.read_sql(
    "SELECT * FROM car_sales",
    engine
)

df.head()

,id_sales,year,brand_car,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,1,2014,Chevrolet,Impala Limited,LT Fleet,Sedan,automatic,2g1wb5e37e1112559,fl,4.0,21507.0,white,black,gm remarketing,13450.0,13800.0,Mon Feb 23 2015 05:00:00 GMT-0800 (PST)
1,2,2003,Dodge,Ram Pickup 1500,SLT,Quad Cab,,1d7ha18n13s152972,mo,31.0,79712.0,—,black,tdaf remarketing,6025.0,6300.0,Tue Jan 20 2015 02:30:00 GMT-0800 (PST)
2,3,2007,Pontiac,G6,GT,Convertible,automatic,1g2zh361474252178,nj,34.0,65698.0,red,black,car authority inc,7375.0,8000.0,Wed Jan 14 2015 01:30:00 GMT-0800 (PST)
3,4,2011,Toyota,Corolla,LE,Sedan,automatic,jtdbu4eexb9167571,fl,43.0,23634.0,black,beige,world omni financial corporation,10800.0,11400.0,Tue Jan 27 2015 01:30:00 GMT-0800 (PST)
4,5,2012,Lexus,ES 350,Base,Sedan,,jthbk1eg6c2495519,pa,35.0,26483.0,black,brown,meridian remarketing,22500.0,23300.0,Fri Jan 30 2015 01:00:00 GMT-0800 (PST)

In [3]:
df.shape

(30000, 17)

In [4]:
df.isnull().sum()

id_sales          0
year              0
brand_car         0
model             0
trim              0
body              0
transmission      0
vin               0
state             0
condition       659
odometer          7
color             0
interior          0
seller            0
mmr               2
sellingprice      0
saledate          0
dtype: int64

In [5]:
df.dtypes

id_sales          int64
year              int64
brand_car        object
model            object
trim             object
body             object
transmission     object
vin              object
state            object
condition       float64
odometer        float64
color            object
interior         object
seller           object
mmr             float64
sellingprice    float64
saledate         object
dtype: object

In [6]:
df.describe()

,id_sales,year,condition,odometer,mmr,sellingprice
count,30000.000000,30000.000000,29341.000000,29993.000000,29998.000000,30000.000000
mean,15000.500000,2010.042100,30.765482,68251.487547,13750.143343,13587.186067
std,8660.398374,3.975616,13.417235,53430.661298,9690.636769,9729.455229
min,1.000000,1985.000000,1.000000,1.000000,25.000000,100.000000
25%,7500.750000,2007.000000,24.000000,27926.000000,7050.000000,6900.000000
50%,15000.500000,2012.000000,35.000000,51923.000000,12300.000000,12200.000000
75%,22500.250000,2013.000000,42.000000,99277.000000,18300.000000,18200.000000
max,30000.000000,2015.000000,49.000000,999999.000000,146000.000000,154000.000000